packages:
  - 'apps/*'
  - 'packages/*'
  - 'services/*'
overrides:
  qs: 6.15.2
  '@hono/node-server': '>=1.19.13'
  uuid: '>=11.1.1'
allowBuilds:
  '@alicloud/openapi-core': true
  '@nestjs/core': true
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
