export const productionRoutePatterns = [
  '/', '/login', '/member/qr-login', '/upload/phone', '/legal/:doc',
  '/resume/job-fit', '/resume/career-plan', '/interview/setup',
  '/interview/session', '/interview/report', '/interview/tips',
  '/interview/reports', '/screensaver', '/session-timeout', '/error-offline',
  '/assistant', '/profile', '/me/resumes', '/me/print-orders', '/me/documents',
  '/me/favorites', '/me/ai-records', '/me/benefits', '/me/activity',
  '/me/activity/:id', '/me/notifications', '/me/feedback', '/me/settings',
  '/me/privacy-requests',
  '/help', '/activities', '/activities/:id', '/renshi', '/campus',
  '/campus/welcome', '/campus/freshman-insights', '/toolbox', '/smart-campus',
  '/smart-campus/welcome', '/smart-campus/freshman-insights',
  '/smart-campus/service/:key', '/print-scan', '/print-scan/feature/:key',
  '/print-scan/convert', '/print-scan/sign', '/print/scan-convert',
  '/print/scan-sign', '/print/scan-feature', '/print/upload',
  '/print/material-check', '/print/preview', '/print/params', '/print/confirm',
  '/print/cashier', '/print/progress', '/print/done', '/resume',
  '/resume/upload', '/resume/source', '/resume/generate',
  '/resume/generate/preview', '/resume/parse', '/resume/report',
  '/resume/optimize', '/resume/export', '/resume/templates', '/resume/materials',
  '/scan/start', '/scan/settings', '/scan/progress', '/scan/result', '/jobs',
  '/jobs/:id', '/jobs/:id/offline', '/offline-agencies', '/offline-agencies/:id', '/notifications',
  '/companies', '/companies/:id', '/job-fairs', '/job-fairs/checkin',
  '/job-fairs/:id', '/job-fairs/:id/companies',
  '/job-fairs/:id/companies/:companyId', '/job-fairs/:id/map',
  '/job-fairs/:id/materials', '/job-fairs/:id/visit-plan',
  '/job-fairs/:id/stats',
  // v1：自我探索 · 倾向参考（PR ③）
  '/resume/self-assessment/intro',
  '/resume/self-assessment/questions',
  '/resume/self-assessment/result',
  '/resume/self-assessment/history',
  // 打印取件认领
  '/print/pickup-claim',
  // PR #496 (AI OS 三新路由)
  '/ai/plan',
  '/session-resume',
  '/jobs/online-platforms',
] as const // 96 routes (was 93)

export const compatibilityRedirects = {
  '/print/scan-convert': '/print-scan/convert',
  '/print/scan-sign': '/print-scan/sign',
  '/print/scan-feature': '/print-scan/feature/id-photo',
  '/resume': '/resume/source',
  '/resume/upload': '/resume/source',
} as const
