// 精简拼音词库（离线内置，懒加载 chunk）。
//
// 定位：覆盖 AI 助手 / 求职一体机高频提问用词 + 常用单字兜底；不追求完整 IME。
// 生僻字词打不出属已知限制——可后续用构建脚本从完整词库（搜狗/Google 拼音）
// 生成更大的 dict.json 替换本文件。查询走「全拼精确 → 前缀 → 首音节单字」。
//
// key = 全拼小写（不含声调/隔音符）；value = 候选，按常用度排序。

// ── 高频词（求职场景 + 通用口语）──────────────────────────────
const WORDS: Record<string, string[]> = {
  jianli: ['简历'],
  youhua: ['优化'],
  zhenduan: ['诊断'],
  mianshi: ['面试'],
  gangwei: ['岗位'],
  zhaopin: ['招聘'],
  zhaopinhui: ['招聘会'],
  dayin: ['打印'],
  saomiao: ['扫描'],
  zhengce: ['政策'],
  shebao: ['社保'],
  butie: ['补贴'],
  dangan: ['档案'],
  gongzi: ['工资'],
  xinzi: ['薪资'],
  xinshui: ['薪水'],
  fuli: ['福利'],
  hetong: ['合同'],
  shixi: ['实习'],
  quanzhi: ['全职'],
  jianzhi: ['兼职'],
  yingjiesheng: ['应届生'],
  gongzuo: ['工作'],
  jingyan: ['经验'],
  jineng: ['技能'],
  xiangmu: ['项目'],
  jiaoyu: ['教育'],
  xueli: ['学历'],
  zhuanye: ['专业'],
  gerenxinxi: ['个人信息'],
  lianxi: ['联系'],
  fangshi: ['方式'],
  ziwo: ['自我'],
  pingjia: ['评价'],
  qiuzhi: ['求职'],
  yixiang: ['意向'],
  gongsi: ['公司'],
  qiye: ['企业'],
  danwei: ['单位'],
  toudi: ['投递'],
  yuyue: ['预约'],
  baoming: ['报名'],
  qiandao: ['签到'],
  weizhi: ['未知', '位置'],
  wenti: ['问题'],
  bangzhu: ['帮助'],
  jianyi: ['建议'],
  ruhe: ['如何'],
  zenme: ['怎么'],
  zenyang: ['怎样'],
  weishenme: ['为什么'],
  shenme: ['什么'],
  naxie: ['哪些'],
  nali: ['哪里'],
  keyi: ['可以'],
  xuyao: ['需要'],
  yinggai: ['应该'],
  zhidao: ['知道'],
  bangwo: ['帮我'],
  woxiang: ['我想'],
  wode: ['我的'],
  nide: ['你的'],
  meiyou: ['没有'],
  zhege: ['这个'],
  nage: ['那个'],
  xiaqiu: ['下求'],
  gaijin: ['改进'],
  xiugai: ['修改'],
  tigao: ['提高'],
  tuijian: ['推荐'],
  zhunbei: ['准备'],
  liuyi: ['留意'],
  zhuyi: ['注意'],
  cailiao: ['材料'],
  wendang: ['文档'],
  geshi: ['格式'],
  moban: ['模板'],
  daoru: ['导入'],
  shangchuan: ['上传'],
  xiazai: ['下载'],
  baocun: ['保存'],
  fenxi: ['分析'],
  pipei: ['匹配'],
  guihua: ['规划'],
  zhiye: ['职业'],
  fazhan: ['发展'],
  fangxiang: ['方向'],
  xiaoqing: ['小青'],
  nihao: ['你好'],
  xiexie: ['谢谢'],
  haode: ['好的'],
  keneng: ['可能'],
  yijing: ['已经'],
  haishi: ['还是'],
  yinwei: ['因为'],
  suoyi: ['所以'],
  danshi: ['但是'],
  ruguo: ['如果'],
  yingpin: ['应聘'],
  luyong: ['录用'],
  ruzhi: ['入职'],
  lizhi: ['离职'],
  shiyongqi: ['试用期'],
  gongjijin: ['公积金'],
}

// ── 常用单字（按音节；覆盖高频字，逐字可打）──────────────────
const CHARS: Record<string, string[]> = {
  a: ['啊', '阿'],
  ai: ['爱', '哎', '唉'],
  ba: ['把', '吧', '八', '爸'],
  bu: ['不', '部', '步', '布'],
  ban: ['办', '半', '班'],
  bao: ['报', '保', '包'],
  bi: ['比', '笔', '必'],
  bian: ['便', '边', '变'],
  bie: ['别'],
  cai: ['才', '材', '菜', '财'],
  chang: ['长', '场', '常', '厂'],
  chu: ['出', '处', '初'],
  ci: ['次', '此', '词'],
  da: ['大', '打', '答'],
  dao: ['到', '道', '倒'],
  de: ['的', '得', '德'],
  deng: ['等', '登', '灯'],
  di: ['第', '地', '低', '底'],
  dian: ['点', '电', '店'],
  dong: ['东', '动', '懂'],
  dou: ['都', '斗'],
  dui: ['对', '队'],
  duo: ['多', '朵'],
  er: ['而', '二', '儿'],
  fa: ['发', '法'],
  fan: ['反', '饭', '烦', '范'],
  fang: ['方', '放', '房', '访'],
  fen: ['分', '份'],
  feng: ['风', '封', '峰'],
  fu: ['服', '福', '副', '付'],
  gai: ['改', '该', '盖'],
  gan: ['干', '感', '敢'],
  gao: ['高', '搞', '告'],
  ge: ['个', '各', '格'],
  gei: ['给'],
  gong: ['工', '公', '共', '功'],
  guan: ['关', '管', '观'],
  gui: ['规', '贵', '归'],
  guo: ['过', '国', '果'],
  hai: ['还', '海', '孩'],
  hao: ['好', '号', '毫'],
  he: ['和', '何', '合', '喝'],
  hen: ['很', '狠'],
  hou: ['后', '候', '厚'],
  hui: ['会', '回', '汇'],
  ji: ['几', '机', '及', '记', '急'],
  jia: ['家', '加', '价', '假'],
  jian: ['见', '件', '简', '建', '检'],
  jiao: ['教', '叫', '交', '较'],
  jie: ['接', '解', '结', '街'],
  jin: ['进', '近', '金', '今'],
  jing: ['经', '精', '境', '井'],
  jiu: ['就', '久', '九', '旧'],
  ju: ['句', '举', '据', '局'],
  kai: ['开'],
  kan: ['看', '砍'],
  ke: ['可', '课', '客', '刻'],
  kou: ['口', '扣'],
  lai: ['来'],
  le: ['了', '乐'],
  li: ['里', '力', '例', '理', '历'],
  liang: ['两', '量', '亮'],
  liao: ['了', '料'],
  ling: ['另', '零', '领'],
  liu: ['留', '六', '流'],
  lu: ['路', '录', '陆'],
  ma: ['吗', '妈', '马'],
  me: ['么'],
  mei: ['没', '每', '美', '妹'],
  men: ['们', '门'],
  mian: ['面', '免'],
  ming: ['名', '明', '命'],
  na: ['那', '哪', '拿'],
  ne: ['呢'],
  neng: ['能'],
  ni: ['你', '呢', '泥'],
  nian: ['年', '念'],
  qi: ['起', '其', '期', '气', '七'],
  qian: ['前', '钱', '签', '千'],
  qing: ['请', '青', '情', '清'],
  qu: ['去', '取', '区'],
  quan: ['全', '权'],
  ran: ['然', '燃'],
  rang: ['让'],
  re: ['热'],
  ren: ['人', '认', '任'],
  ri: ['日'],
  rong: ['容', '荣'],
  ru: ['如', '入'],
  san: ['三', '散'],
  shang: ['上', '商', '伤'],
  shao: ['少', '烧'],
  she: ['社', '设', '舍'],
  shei: ['谁'],
  shen: ['什', '身', '深', '申'],
  sheng: ['生', '省', '声', '胜'],
  shi: ['是', '时', '事', '十', '使', '市', '识', '试'],
  shou: ['手', '收', '受', '首'],
  shu: ['数', '书', '术', '树'],
  shui: ['水', '税', '睡'],
  shuo: ['说'],
  si: ['四', '死', '思', '司'],
  song: ['送'],
  suan: ['算'],
  sui: ['岁', '虽', '随'],
  ta: ['他', '她', '它'],
  tai: ['太', '台'],
  tian: ['天', '填', '田'],
  ting: ['听', '停', '厅'],
  tong: ['同', '通', '统'],
  tou: ['头', '投'],
  wai: ['外'],
  wan: ['万', '完', '玩', '晚'],
  wang: ['网', '往', '望', '王'],
  wei: ['为', '位', '未', '委', '喂'],
  wen: ['问', '文', '闻'],
  wo: ['我', '握'],
  wu: ['无', '五', '物', '务'],
  xi: ['系', '西', '细', '习', '喜'],
  xia: ['下', '吓'],
  xian: ['先', '现', '线', '县'],
  xiang: ['想', '向', '像', '相', '项'],
  xie: ['些', '写', '谢', '鞋'],
  xin: ['信', '新', '心', '薪'],
  xing: ['行', '性', '型', '姓'],
  xu: ['需', '许', '续'],
  xue: ['学', '雪'],
  ya: ['呀', '压'],
  yan: ['验', '眼', '言', '严'],
  yang: ['样', '养', '阳'],
  yao: ['要', '药', '摇'],
  ye: ['也', '业', '页', '夜'],
  yi: ['一', '以', '意', '已', '医', '衣'],
  yin: ['因', '音', '银', '印'],
  ying: ['应', '英', '影', '硬'],
  yong: ['用', '永'],
  you: ['有', '又', '右', '优', '由'],
  yu: ['于', '与', '语', '育', '遇'],
  yuan: ['员', '元', '院', '原', '愿'],
  yue: ['月', '约', '越'],
  zai: ['在', '再', '载'],
  zao: ['早', '造'],
  ze: ['则', '责'],
  zen: ['怎'],
  zhe: ['这', '着', '者'],
  zhen: ['真', '诊', '针'],
  zheng: ['正', '整', '政', '证'],
  zhi: ['之', '只', '知', '职', '直', '制', '至'],
  zhong: ['中', '种', '重', '众'],
  zhu: ['主', '住', '注', '助'],
  zhuan: ['专', '转', '赚'],
  zi: ['自', '字', '资', '子'],
  zong: ['总', '综'],
  zou: ['走'],
  zui: ['最', '嘴'],
  zuo: ['做', '作', '坐', '左'],
}

// 全拼精确 → 前缀（词优先）→ 首音节单字兜底
export function queryCandidates(py: string, limit = 9): string[] {
  const s = py.toLowerCase().replace(/[^a-z]/g, '')
  if (!s) return []

  const out: string[] = []
  const push = (arr?: string[]) => {
    if (!arr) return
    for (const w of arr) if (!out.includes(w)) out.push(w)
  }

  // 1) 全拼精确（词 + 单字）
  push(WORDS[s])
  push(CHARS[s])

  // 2) 前缀匹配（词优先，按长度升序更相关）
  if (out.length < limit) {
    const prefixed = Object.keys(WORDS)
      .filter((k) => k !== s && k.startsWith(s))
      .sort((a, b) => a.length - b.length)
    for (const k of prefixed) push(WORDS[k])
  }
  if (out.length < limit) {
    const prefixedChars = Object.keys(CHARS)
      .filter((k) => k !== s && k.startsWith(s))
      .sort((a, b) => a.length - b.length)
    for (const k of prefixedChars) push(CHARS[k])
  }

  // 3) 首音节单字兜底（连打时取能匹配的最长首音节）
  if (out.length === 0) {
    for (let len = Math.min(s.length, 6); len >= 1; len--) {
      const head = s.slice(0, len)
      if (CHARS[head]) {
        push(CHARS[head])
        break
      }
    }
  }

  return out.slice(0, limit)
}
