export const PAYLOAD_LABELS: Record<string, string> = {
  billablePages: '计费页数',
  terminalCode: '终端编号',
  terminalIds: '终端列表',
  terminalCodes: '终端编号列表',
  taskType: '任务类型',
  taskId: '任务编号',
  pages: '页数',
  colorMode: '色彩模式',
  paperSize: '纸张规格',
  orientation: '纸张方向',
  source: '来源',
  sourceId: '来源编号',
  sourceOrgId: '来源机构编号',
  sourceName: '来源名称',
  before: '变更前',
  after: '变更后',
  attempted: '尝试变更',
  changedFields: '变更字段',
  changed: '变更项',
  portal: '登录入口',
  secondFactor: '二次验证方式',
  codeSent: '是否发送验证码',
  name: '名称',
  title: '标题',
  note: '说明',
  notes: '说明',
  reviewStatus: '审核状态',
  publishStatus: '发布状态',
  reviewReason: '审核原因',
  reviewAction: '审核操作',
  unpublishReason: '下架原因',
  archiveReason: '归档原因',
  archived: '是否归档',
  actorId: '操作人编号',
  actorRole: '操作人角色',
  operatorName: '操作人姓名',
  contentType: '内容类型',
  targetType: '对象类型',
  targetId: '对象编号',
  targetIds: '对象列表',
  orgName: '机构名称',
  partnerName: '机构账号名称',
  fileIds: '文件列表',
  mimeType: '文件类型',
  sizeBytes: '文件大小（字节）',
  purpose: '文件用途',
  retentionDays: '保存天数',
  retentionMode: '保存方式',
  vendor: '模型厂商',
  model: '模型名称',
  baseURL: '模型服务地址',
  temperature: '模型温度',
  operation: 'AI 功能',
  provider: 'AI 提供方',
  statusCode: '状态码',
  errorCode: '错误码',
  errorMessage: '错误信息',
  latencyMs: '耗时（毫秒）',
  amount: '金额',
  currency: '币种',
  paidAmountCents: '实付金额（分）',
  refundAmountCents: '退款金额（分）',
  refundId: '退款编号',
  refundNo: '退款单号',
  paymentId: '支付编号',
  channel: '支付渠道',
  payStatus: '支付状态',
  orderStatus: '订单状态',
  printOutcome: '出纸核查结果',
  closeReason: '关闭原因',
  retryCount: '重试次数',
  attemptId: '支付尝试编号',
  activityId: '活动编号',
  benefitId: '权益编号',
  packageId: '套餐编号',
  quantity: '数量',
  oldStatus: '原状态',
  newStatus: '新状态',
  oldOrgId: '原机构编号',
  newOrgId: '新机构编号',
  oldEnabled: '原启用状态',
  newEnabled: '新启用状态',
  previousStatus: '原状态',
  nextStatus: '新状态',
  requestId: '请求编号',
  requestType: '申请类型',
  exportId: '导出编号',
  downloadConsumedAt: '下载领取时间',
  exportExpiresAt: '导出到期时间',
  createdAt: '创建时间',
  updatedAt: '更新时间',
  completedAt: '完成时间',
  startedAt: '开始时间',
  expiresIn: '有效秒数',
  scope: '操作范围',
  mode: '模式',
  method: '操作方式',
  host: '域名',
  url: '地址',
  appId: '应用编号',
  versionId: '版本编号',
  version: '版本',
  configId: '配置编号',
  capabilityKey: '能力项',
  statusReason: '状态说明',
  terminalCount: '终端数量',
  successCount: '成功数量',
  failedCount: '失败数量',
  addedCount: '新增数量',
  updatedCount: '更新数量',
  errorCount: '错误数量',
  unlabeledApplied: '是否已去标识',
  hasParams: '是否记录参数',
  hasPhone: '是否登记手机号',
  truncated: '是否截断',
  batchId: '批次编号',
  reasonCode: '原因码',
  from: '原值',
  to: '新值',
  ids: '对象编号列表',
  reason: '原因', fromStatus: '原状态', toStatus: '新状态', sections: '查看范围',
  matched: '是否找到用户', queryType: '查询方式', fileId: '文件编号', fileName: '文件名',
  sourceFileId: '原文件编号', hasFileHash: '是否记录文件校验值', params: '打印参数',
  hasEndUser: '是否为登录用户', terminalId: '终端编号', orderId: '订单编号', orderNo: '订单号',
  partnerId: '机构账号编号', orgId: '机构编号', userId: '账号编号', endUserId: '用户编号',
  count: '数量', deletedCount: '删除数量', expiresAt: '过期时间', status: '状态',
  result: '结果', phase: '步骤', copies: '份数', duplex: '双面', color: '彩色',
  pageRange: '页范围', amountCents: '金额（分）', phoneMasked: '手机号',
  phone: '手机号', contactPhone: '联系电话', mobile: '手机号', email: '邮箱',
  password: '密码', token: '令牌', accessToken: '访问令牌', refreshToken: '刷新令牌',
  apiKey: '接口密钥', secret: '密钥', authorization: '身份验证信息', cookie: '登录凭据',
  action: '操作', rows: '行数', cleaned: '清理数量', enabled: '是否启用', field: '变更字段',
  type: '类型', commandId: '命令编号', resultCode: '结果代码', remainingJobs: '剩余作业数',
}

