/* ── Utility ──────────────────────────────────────────── */
export { cn } from './lib/cn'
export { getVisualThemeAttributes } from './theme/visualTheme'
export { getKioskPresentationAttributes } from './theme/visualTheme'

/* ── Base components ──────────────────────────────────── */
export { Button, buttonVariants } from './components/Button'
export { Card } from './components/Card'
export { StatusBadge, badgeVariants } from './components/StatusBadge'
export { PageHeader } from './components/PageHeader'
export { ComplianceBanner } from './components/ComplianceBanner'
export { Stepper } from './components/Stepper'
export { Drawer } from './components/Drawer'
export { Pagination } from './components/Pagination'
export { SectionCard } from './components/SectionCard'
export { Meter } from './components/Meter'
export { KioskPageFrame } from './components/KioskPageFrame'
export { KioskPageHeader } from './components/KioskPageHeader'
export { KioskActionBar } from './components/KioskActionBar'
export { KioskStatePanel } from './components/KioskStatePanel'
export { KioskModal } from './components/KioskModal'

/* ── Charts (recharts) ────────────────────────────────── */
export { ResumeRadarChart } from './charts/ResumeRadarChart'
export { TrendLineChart } from './charts/TrendLineChart'
export { FunnelCard } from './charts/FunnelCard'
export { MetricGrid } from './charts/MetricGrid'

/* ── State components ─────────────────────────────────── */
export { Spinner } from './components/Spinner'
export { EmptyState } from './components/EmptyState'
export { LoadingState } from './components/LoadingState'
export { ErrorState } from './components/ErrorState'

/* ── Layout components ────────────────────────────────── */
export { KioskLayout } from './layouts/KioskLayout'
export { AdminLayout } from './layouts/AdminLayout'
export { PartnerLayout } from './layouts/PartnerLayout'

/* ── Types ────────────────────────────────────────────── */
export type { ButtonProps } from './components/Button'
export type { CardProps } from './components/Card'
export type { StatusBadgeProps } from './components/StatusBadge'
export type { PageHeaderProps } from './components/PageHeader'
export type { ComplianceBannerProps } from './components/ComplianceBanner'
export type { StepperProps, StepperStep } from './components/Stepper'
export type { DrawerProps } from './components/Drawer'
export type { PaginationProps } from './components/Pagination'
export type { SectionCardProps } from './components/SectionCard'
export type { MeterProps } from './components/Meter'
export type { KioskPageFrameProps } from './components/KioskPageFrame'
export type { KioskPageHeaderProps } from './components/KioskPageHeader'
export type { KioskActionBarProps } from './components/KioskActionBar'
export type { KioskStatePanelProps, KioskStateTone } from './components/KioskStatePanel'
export type { KioskModalProps } from './components/KioskModal'
export type { ResumeRadarChartProps, ResumeRadarDimension, ResumeRadarSeries } from './charts/ResumeRadarChart'
export type { TrendLineChartProps, TrendSeries } from './charts/TrendLineChart'
export type { FunnelCardProps, FunnelStep } from './charts/FunnelCard'
export type { MetricGridProps, MetricItem } from './charts/MetricGrid'
export type { SpinnerProps } from './components/Spinner'
export type { EmptyStateProps } from './components/EmptyState'
export type { LoadingStateProps } from './components/LoadingState'
export type { ErrorStateProps } from './components/ErrorState'
export type { VisualTheme, UiDensity } from './theme/visualTheme'
export type { KioskPresentation, KioskViewport } from './theme/visualTheme'
export type { KioskLayoutProps, KioskTab } from './layouts/KioskLayout'
export type { AdminLayoutProps, NavItem } from './layouts/AdminLayout'
export type { PartnerLayoutProps } from './layouts/PartnerLayout'
