import type { ServiceHubKey, ServiceHubSpec } from './serviceHubModel'

/**
 * 五份规格**机械抽自** docs/design/kiosk-redesign-2026-08/16-service-hubs.html 的 `const H`，
 * 不是手抄的。手抄是漏掉诚实性声明最常见的来源——这批迁移里已经因为手抄漏过多次。
 * 稿改了要重抽，别手改这个文件。
 */
export const SERVICE_HUB_SPECS: Record<ServiceHubKey, ServiceHubSpec> = {
  resume: {
    eyebrow: 'AI简历服务',
    title: '把简历这件事，做得更清楚',
    subtitle: '从来源选择、诊断优化到生成、材料与打印，按你的目标进入对应步骤。',
    goals: [
      { label: '我有简历要体检', route: '/resume/source?intent=diagnose' },
      { label: '我没简历要新建', route: '/resume/generate' },
      { label: '我要对着岗位改', route: '/resume/source?intent=optimize' },
    ],
    sectionTitle: '八项简历能力',
    sectionHint: '先选目标，再进入真实流程',
    capabilities: [
      { title: 'AI简历诊断', description: '先选简历来源，再查看结构与问题', badge: 'AI · 仅供参考', route: '/resume/source?intent=diagnose', kind: 'ai' },
      { title: 'AI简历优化', description: '选择目标岗位后逐条查看改写建议', badge: 'AI · 仅供参考', route: '/resume/source?intent=optimize', kind: 'ai' },
      { title: '从零生成简历', description: '按引导补充信息，生成可核对草稿', badge: 'AI · 需核对', route: '/resume/generate', kind: 'ai' },
      { title: '简历素材库', description: '按分类查看真实模板、标签与适用场景', badge: '模板目录', route: '/resume/templates', kind: 'info' },
      { title: '职业规划', description: '基于真实经历与目标生成行动建议', badge: 'AI · 仅供参考', route: '/resume/career-plan', kind: 'ai' },
      { title: '求职材料', description: '准备求职信、自我介绍与材料清单', badge: 'AI · 需核对', route: '/resume/materials', kind: 'ai' },
      { title: '简历打印', description: '选择文件、核价后在本机打印', badge: '依赖打印机', route: '/print/upload?source=resume', kind: 'device' },
      { title: '岗位匹配参考', description: '简历与岗位逐项对照，不给录用结论', badge: 'AI · 不给百分比', route: '/resume/job-fit', kind: 'ai' },
    ],
    truthTitle: '简历是否使用、投给谁，由你本人决定。',
    truth: '系统不代投、不替企业筛选或邀约。',
    noteTitle: '原件始终由你掌控',
    note: 'AI建议仅供参考，新版本不会覆盖原文件。',
  },
  jobs: {
    eyebrow: '岗位信息',
    title: '看清来源，再决定去哪里投',
    subtitle: '岗位来自第三方或官方来源。本机帮助筛选和理解，投递仍在来源平台完成。',
    goals: [
      { label: '找全职', route: '/jobs?category=fulltime' },
      { label: '找实习', route: '/jobs?category=intern' },
      { label: '找校招', route: '/jobs?category=campus' },
      { label: '找兼职', route: '/jobs?category=parttime' },
    ],
    sectionTitle: '岗位与来源入口',
    sectionHint: '岗位以进入后的真实加载为准',
    capabilities: [
      { title: '全职岗位', description: '按行业、地区与薪资范围筛选', badge: '第三方来源', route: '/jobs?category=fulltime', kind: 'info' },
      { title: '实习岗位', description: '查看面向在校生与应届生的机会', badge: '第三方来源', route: '/jobs?category=intern', kind: 'info' },
      { title: '兼职信息', description: '查看灵活就业与兼职来源信息', badge: '第三方来源', route: '/jobs?category=parttime', kind: 'info' },
      { title: '校园招聘岗位', description: '查看经审核发布的校招来源岗位', badge: '第三方来源', route: '/jobs?category=campus', kind: 'info' },
      { title: '全部岗位', description: '搜索并查看全部已审核来源岗位', badge: '真实加载', route: '/jobs', kind: 'info' },
      { title: '企业信息', description: '先了解企业，再查看岗位来源', badge: '来源信息', route: '/companies', kind: 'info' },
      { title: '岗位匹配参考', description: '简历与目标岗位逐项对照', badge: 'AI · 仅供参考', route: '/resume/job-fit', kind: 'ai' },
      { title: '线上招聘平台', description: '打开第三方平台，由你自行操作', badge: '外部来源', route: '/jobs/online-platforms', kind: 'info' },
      { title: '线下招聘机构', description: '查看机构地址与到店咨询指引', badge: '线下咨询', route: '/offline-agencies', kind: 'info' },
    ],
    truthTitle: '投递在来源平台完成。',
    truth: '本机记录你的浏览与外部跳转；投递进度由你自己填写，本机不掌握来源平台的处理结果。',
    noteTitle: '本机不代收简历',
    note: '不做企业筛选、面试邀约或Offer管理。',
  },
  fairs: {
    eyebrow: '招聘会',
    title: '先看场次，再准备到场',
    subtitle: '查看招聘会时间、地点和来源，准备简历与路线；预约在来源平台完成。',
    goals: [
      { label: '找近期场次', route: '/job-fairs' },
      { label: '准备到场', route: '/job-fairs/checkin' },
      { label: '准备材料', route: '/print-scan' },
    ],
    sectionTitle: '招聘会服务',
    sectionHint: '六个入口，覆盖会前与现场准备',
    capabilities: [
      { title: '招聘会列表', description: '查看真实场次、时间、地点与来源', badge: '真实加载', route: '/job-fairs', kind: 'info' },
      { title: '校园招聘', description: '查看校园相关场次与企业信息', badge: '真实加载', route: '/campus', kind: 'info' },
      { title: '到场指引', description: '核对来源预约与现场流程', badge: '无签到回执', route: '/job-fairs/checkin', kind: 'info' },
      { title: '问AI顾问', description: '了解参会准备与现场沟通建议', badge: 'AI · 仅供参考', route: '/assistant', kind: 'ai' },
      { title: '简历服务', description: '诊断、优化或准备多份简历', badge: '进入简历中心', route: '/resume-service', kind: 'info' },
      { title: '打印扫描', description: '先查看文件、格式与办理入口；出纸或扫描步骤进入后确认', badge: '进入后确认', route: '/print-scan', kind: 'info' },
    ],
    truthTitle: '预约和投递由来源平台负责。',
    truth: '本机不代收简历，也不承诺外部活动结果。',
    noteTitle: '不显示虚构签到结果',
    note: '场次、参会企业和地图均以真实数据为准。',
  },
  interview: {
    eyebrow: 'AI面试训练',
    title: '把表达练熟，不替你下结论',
    subtitle: '模拟问答、自我探索、技巧与历史报告，用于练习和复盘，不代表真实面试结果。',
    goals: [
      { label: '马上练一场', route: '/interview/setup' },
      { label: '先看技巧', route: '/interview/tips' },
      { label: '回看报告', route: '/interview/reports' },
    ],
    sectionTitle: '面试与成长',
    sectionHint: '六个入口，按练习目标进入',
    capabilities: [
      { title: '开始模拟面试', description: '选择岗位类型与难度后进入训练', badge: 'AI · 练习', route: '/interview/setup', kind: 'ai' },
      { title: '职业自我探索', description: '了解优势、偏好与可尝试方向', badge: 'AI · 仅供参考', route: '/resume/self-assessment/intro', kind: 'ai' },
      { title: '职业规划建议', description: '根据经历与目标形成行动建议', badge: 'AI · 仅供参考', route: '/resume/career-plan', kind: 'ai' },
      { title: '面试技巧', description: '查看通用问答与沟通要点', badge: '静态内容', route: '/interview/tips', kind: 'info' },
      { title: '评估历史', description: '回看本人历次自我探索结果', badge: '本人记录', route: '/resume/self-assessment/history', kind: 'info' },
      { title: '行业薪资参考', description: '向通用AI顾问询问市场信息', badge: 'AI · 需核实', route: '/assistant', kind: 'ai' },
    ],
    truthTitle: 'AI训练不是企业面试。',
    truth: '不进行录用判断，不向企业推荐候选人。',
    noteTitle: '不排名，不预测录用',
    note: '报告仅供本人练习参考，不对外共享。',
  },
  policy: {
    eyebrow: '政策服务',
    title: '看来源、查条件、备材料',
    subtitle: '就业政策、社保与档案登记以来源内容为准；AI顾问只做通用说明。',
    goals: [
      { label: '找就业政策', route: '/renshi?tab=policy' },
      { label: '核对申领条件', route: '/renshi?tab=eligibility' },
      { label: '查社保材料', route: '/renshi?tab=social' },
      { label: '看登记档案', route: '/renshi?tab=register' },
    ],
    sectionTitle: '政策与办事指引',
    sectionHint: '六个入口，来源与条件分开看',
    capabilities: [
      { title: '就业政策', description: '查看就业、创业与灵活就业政策', badge: '来源内容', route: '/renshi?tab=policy', kind: 'info' },
      { title: '社保指南', description: '查看参保流程与材料说明', badge: '确定性内容', route: '/renshi?tab=social', kind: 'info' },
      { title: '档案与登记', description: '查看托管、登记和证明材料', badge: '确定性内容', route: '/renshi?tab=register', kind: 'info' },
      { title: '条件核对', description: '按 9 项真实问项机械比对，不作资格认定', badge: '确定性规则', route: '/renshi?tab=eligibility', kind: 'info' },
      { title: '政策公告', description: '查看发布方公告、来源与发布日期', badge: '来源内容', route: '/renshi?tab=notice', kind: 'info' },
      { title: '打开AI顾问', description: '咨询通用政策说明并核对来源', badge: 'AI · 需核实', route: '/assistant', kind: 'ai' },
      { title: '政策收藏', description: '查看本人收藏的政策内容', badge: '本人记录', route: '/me/favorites?tab=policy', kind: 'info' },
    ],
    truthTitle: '政策内容以来源发布为准。',
    truth: 'AI顾问不替主管部门作资格判断。',
    noteTitle: '不承诺办理或资格结果',
    note: '资格核对使用确定性规则，最终以官方审核为准。',
  },
}
